### ISSUE TITLE
Unexpected panic during data processing with cloudevents

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fdk-go#23]
```
cat payload.json | fn call app route
{"error":{"message":"container exit code 2"}}
ERROR: error calling function: status 502

❯ fn logs g app last
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
func/vendor/github.com/fnproject/fdk-go/utils.DoCloudEventOnce(0x7f86bdad2fd0, 0x6ad9c8, 0x6ced40, 0xc420074d50, 0x6cc7c0, 0xc42000e010, 0x6cc7e0, 0xc42000e018, 0xc420104000, 0xc420074d80, ...)
    /go/src/func/vendor/github.com/fnproject/fdk-go/utils/cloudevent.go:88 +0x6b9
func/vendor/github.com/fnproject/fdk-go/utils.DoCloudEvent(0x7f86bdad2fd0, 0x6ad9c8, 0x6ced40, 0xc420074d50, 0x6cc7c0, 0xc42000e010, 0x6cc7e0, 0xc42000e018)
    /go/src/func/vendor/github.com/fnproject/fdk-go/utils/cloudevent.go:102 +0xd9
func/vendor/github.com/fnproject/fdk-go/utils.Do(0x7f86bdad2fd0, 0x6ad9c8, 0xc42001606a, 0xa, 0x6cc7c0, 0xc42000e010, 0x6cc7e0, 0xc42000e018)
    /go/src/func/vendor/github.com/fnproject/fdk-go/utils/utils.go:47 +0x1f6
func/vendor/github.com/fnproject/fdk-go.Handle(0x6ccc60, 0x6ad9c8)
    /go/src/func/vendor/github.com/fnproject/fdk-go/fdk.go:81 +0xce
main.main()
    /go/src/func/func.go:20 +0x39
```

**Comment by rdallman** [comment]
i think it's from the snafu where we tried to switch to `text/plain` logs, update fdk version in CLI?

**Comment by denismakogon** [comment]
Here's the problem: 
here ->https://github.com/fnproject/cli/blob/ad8e913ba39b16c8ea655da6a787f4f739869ce6/run.go#L158

subsequent problem ->https://github.com/fnproject/cli/blob/ad8e913ba39b16c8ea655da6a787f4f739869ce6/run_cloud_event.go#L56

It appears that we default the content type to `application/json` while doing so. I guess FDK should protect itself from such things by doing exactly what Fn does.

**Comment by denismakogon** [comment]
it's in CLI, however, Fn does this type conversion if the content type is `application/json`: https://github.com/fnproject/fn/blob/master/api/agent/protocol/cloudevent.go#L86

**Comment by denismakogon** [comment]
so, this PR still necessary, i suppose.
